apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-bin
  labels:
    system: openstack
    type: configuration
    component: nova
data:
{{ (.Files.Glob "bin/*").AsConfig | indent 2 }}
  common.sh: |
{{ include "common.sh" .| indent 4 }}
  db-migrate: |
{{ include (print .Template.BasePath "/bin/_db-migrate.tpl") . | indent 4 }}
  db-online-migrate: |
{{ include (print .Template.BasePath "/bin/_db-online-migrate.tpl") . | indent 4 }}
{{- if .Values.global.enable_kvm }}
  neutron-ovs-db-start: |
{{ include (print .Template.BasePath "/bin/_neutron-ovs-db-start.tpl") . | indent 4 }}
  neutron-ovs-start: |
{{ include (print .Template.BasePath "/bin/_neutron-ovs-start.tpl") . | indent 4 }}
  neutron-openvswitch-agent-start: |
{{ include (print .Template.BasePath "/bin/_neutron-openvswitch-agent-start.tpl") . | indent 4 }}
{{- end }}
