apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-name": "nova"
    "meta.helm.sh/release-namespace": "monsoon3"
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  name: nova-kvm-shared
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
